# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'TodayHeadline' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Kingfisher', '~> 5.7.1'
  pod 'Moya'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'ObjectMapper', '~> 3.4'
  # Pods for TodayHeadline

end
