# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'TodayHeadline' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Kingfisher', '~> 5.7.1'

  # Pods for TodayHeadline

end
